[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 20

[[main]]
  name = "People"
  pageRef = "/people"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

[[footer]]
  name = "GitHub"
  url = "https://github.com/ML-FGV"
  
[[footer]]
  name = "LinkedIn"
  url = "https://linkedin.com"
