colorScheme = "avocado"
defaultAppearance = "light"
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = true
enableImageLazyLoading = true

[header]
layout = "hybrid"
# logo = "logo.png"
showTitle = true

[footer]
showAppearanceSwitcher = true

[homepage]
layout = "custom"

[list]
showSummary = true
showTaxonomies = true

[article]
showTableOfContents = true
showTaxonomies = true
showReadingTime = false
showWordCount = false
showPagination = true
showAuthor = false
showBreadcrumbs = false
